CHANGE COLUMN price fulfilledprice DECIMAL(10, 2) NOT NULL,
ADD COLUMN budget DECIMAL(10, 2);

ALTER TABLE request
ADD COLUMN breached BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE requestproduct
ADD COLUMN fulfilledDate DATETIME;

CREATE TABLE Team (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL
);
CREATE TABLE UserTeam (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  UserId VARCHAR(255) NOT NULL,
  TeamId INT NOT NULL,
  FOREIGN KEY (UserId) REFERENCES aspnetusers(Id),
  FOREIGN KEY (TeamId) REFERENCES Team(Id)
);

