ALTER TABLE audit_trail MODIFY id INT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE category MODIFY id INT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE email_account MODIFY id INT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE email_queue MODIFY id INT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE product MODIFY id INT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE productcategory MODIFY id INT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE request MODIFY id INT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE request
MODIFY COLUMN ManagerId VARCHAR(50);

CREATE TABLE RequestProduct (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  RequestId INT NOT NULL,
  ProductId INT NOT NULL,
  CONSTRAINT FK_RequestProduct_Request FOREIGN KEY (RequestId)
    REFERENCES Request(Id),
  CONSTRAINT FK_RequestProduct_Product FOREIGN KEY (ProductId)
    REFERENCES Product(Id)
);

ALTER TABLE Request
DROP COLUMN ProductId;

ALTER TABLE requestproduct ADD COLUMN quantity INT;

ALTER TABLE request
MODIFY COLUMN TimeToResolution Time;
