CHANGE COLUMN price fulfilledprice DECIMAL(10, 2) NOT NULL,
ADD COLUMN budget DECIMAL(10, 2);

ALTER TABLE request
ADD COLUMN breached BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE requestproduct
ADD COLUMN fulfilledDate DATETIME;

CREATE TABLE Team (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL
);

ALTER TABLE AspNetUsers
ADD TeamId INT,
ADD CONSTRAINT FK_AspNetUsers_Team FOREIGN KEY (TeamId) REFERENCES Team(Id);

ALTER TABLE Request
ADD CustomerName VARCHAR(100),
ADD DealJustification VARCHAR(200);
